set shouldPresentInFullscreen as true
joomcode/BottomSheet pull request #33
Opened 2023-11-07 17:01 UTC by lcanalimp

set shouldPresentInFullscreen as true due iOS 17 known problem

2023-11-07 17:01 UTC, 39otrebla approved these changes

2023-11-07 17:02 UTC, 39otrebla requested changes
Wrong target repo/branch.

2023-11-09 09:21 UTC, mikhailmaslo commented on Sources/BottomSheet/Core/Presentation/BottomSheetPresentationController.swift
> +        true
Should we set it only for IOS 17?

I'm not sure how this flag affects older versions
```Suggestion
        if #available(iOS 17.0, *) {
            return true
        } else {
            return false
        }
```

2023-11-09 09:22 UTC, mikhailmaslo commented
Might address this issues:
- https://github.com/joomcode/BottomSheet/issues/32
- https://github.com/joomcode/BottomSheet/issues/31

2024-01-06 17:13 UTC, mikhailmaslo commented
Finished the same code here https://github.com/joomcode/BottomSheet/pull/38

2024-01-06 17:13 UTC, closed without merging